# Generated by Django 5.0.1 on 2024-02-11 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectfiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailyAccomplishments',
            new_name='DailyAccomplishment',
        ),
        migrations.RenameModel(
            old_name='DailyGoals',
            new_name='DailyGoal',
        ),
        migrations.RenameModel(
            old_name='UserData',
            new_name='UserInfo',
        ),
    ]
