# Generated by Django 5.0.1 on 2024-02-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectfiles', '0002_rename_dailyaccomplishments_dailyaccomplishment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailygoal',
            name='date',
        ),
        migrations.AddField(
            model_name='dailygoal',
            name='attended_time',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
