# Generated by Django 5.0.1 on 2024-02-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectfiles', '0003_remove_dailygoal_date_dailygoal_attended_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyaccomplishment',
            name='date',
        ),
        migrations.AddField(
            model_name='dailyaccomplishment',
            name='finished',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
