# Generated by Django 5.0.1 on 2024-02-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectfiles', '0005_delete_dailyaccomplishment'),
    ]

    operations = [
        migrations.CreateModel(
            name='userRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DailyGoal',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='phone',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
