# Generated by Django 5.0.1 on 2024-02-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectfiles', '0006_userregistration_delete_dailygoal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('username', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='userRegistration',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='name',
            new_name='attended_time',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='username',
            new_name='goals',
        ),
    ]
