# Generated by Django 5.0.1 on 2024-02-15 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectfiles', '0009_data_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='tasks',
            name='doer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectfiles.data'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='tags',
            field=models.ManyToManyField(to='projectfiles.tag'),
        ),
    ]
