# Generated by Django 5.0.1 on 2024-02-15 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectfiles', '0010_tag_tasks_doer_tasks_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='day',
        ),
    ]
