# Generated by Django 5.0.1 on 2024-02-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectfiles', '0011_remove_tasks_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='note',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
