# Generated by Django 5.0.1 on 2024-02-17 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectfiles', '0012_tasks_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='note',
        ),
    ]
