# Generated by Django 5.0.1 on 2024-02-18 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectfiles', '0013_remove_tasks_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='attended_time',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=200, null=True),
        ),
    ]
