# Generated by Django 5.0.1 on 2024-02-18 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectfiles', '0014_tasks_attended_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='doer',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='tags',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='tasks',
        ),
    ]
