# Generated by Django 5.0.1 on 2024-02-25 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectfiles', '0016_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='day',
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
